export {ReactComponent as HeartIcon } from '../../svg/heart.svg'
export {ReactComponent as DownloadIcon } from '../../svg/download.svg'
export {ReactComponent as CopyIcon } from '../../svg/copy.svg'
export {ReactComponent as PaletteIcon } from '../../svg/palette.svg'
export {ReactComponent as FavoriteIcon } from '../../svg/favorite.svg'
export {ReactComponent as LogoIcon } from '../../svg/logo.svg'
export {ReactComponent as LoupeIcon } from '../../svg/loupe.svg'